NDefines.NDiplomacy.DAYS_TO_DECLARE_WAR = 993
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 50
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_DURATION = 8
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 10
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.HEGEMONY_LOST_DAYS = 1825
NDefines.NDiplomacy.MARCH_BASE_DEVELOPMENT_CAP = 500

NDefines.NNationDesigner.RULER_BASE_SKILL = 4
NDefines.NNationDesigner.RULER_MAX_SKILL = 4
NDefines.NNationDesigner.RULER_SKILL_COST_MODIFIER = 0
NDefines.NNationDesigner.GOLD_PROVINCE_COST_MULTIPLIER = 1
NDefines.NNationDesigner.MEMBER_OF_HRE_COST = 0
NDefines.NNationDesigner.MEMBER_OF_HRE_PROVINCE_COST = 0.0
NDefines.NNationDesigner.FLAT_TAX_AMOUNT = 1
NDefines.NNationDesigner.FLAT_MP_AMOUNT = 1
NDefines.NNationDesigner.POINTS_AVAILABLE = 5000

NDefines.NCountry.ALLOW_ESTATE_AND_PARLIAMENT_SEAT_IN_PROVINCE = 1
NDefines.NCountry.ESTATE_LOYALTY_DECAY_BASE_MIN = 1.0
NDefines.NCountry.ESTATE_LOYALTY_DECAY_BASE_MAX = 2.5
NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 8
NDefines.NCountry.STATE_MAINTENANCE_DEV_FACTOR = 0.01
NDefines.NCountry.STATE_MAINTENANCE_DISTANCE_FACTOR = 0.003
NDefines.NCountry.STATE_MAINTENANCE_CONTINENT_FACTOR = 0.25
NDefines.NCountry.STATE_MAINTENANCE_CULTURE_FACTOR = 0.25
NDefines.NCountry.SCRIPTED_ADVISOR_DISCOUNT = 0.5
NDefines.NCountry.PS_BUY_IDEA = 300
NDefines.NCountry.FREE_IDEA_GROUP_COST = 7
NDefines.NCountry.IDEA_TO_TECH = -0.006
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.39
NDefines.NCountry.ABANDON_IDEAGROUP_REFUND = 0.5
NDefines.NCountry.MAX_ACTIVE_POLICIES = 12
NDefines.NCountry.BASE_POSSIBLE_POLICIES = 4
NDefines.NCountry.MINIMUM_POLICY_TIME = 1
NDefines.NCountry.PS_RAISE_TARIFFS = 10
NDefines.NCountry.PS_LOWER_TARIFFS = 5
NDefines.NCountry.DICTATORSHIP_TRADITION_FOR_MONARCHY = 20
NDefines.NCountry.DICTATORSHIP_TRADITION_FOR_REPUBLIC = 60
NDefines.NCountry.MONARCH_MIN_SKILL = 2

NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.03
NDefines.NEconomy.BASE_INTERESTS = 5.0
NDefines.NEconomy.CARAVAN_FACTOR = 20.0
NDefines.NEconomy.CARAVAN_POWER_MAX = 10
NDefines.NEconomy.MAX_BUILDING_SLOTS = 18

NDefines.NMilitary.NAVAL_BASE_ENGAGEMENT_WIDTH = 40
NDefines.NMilitary.NAVAL_CASUALTY_MIN_MORALE_DAMAGE = 0.0
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 50
NDefines.NMilitary.CREATE_JANISSARIES_MIL_COST = 5
NDefines.NMilitary.COMBAT_DICE_SIDE = 8

NDefines.NAI.GREAT_POWER_ACTIONS_DISABLE_VERSUS_PLAYER = 1
NDefines.NAI.AGGRESSIVENESS = 1
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 1
NDefines.NAI.DIPLOMATIC_ACTION_ENFORCE_PEACE_FORCE_BALANCE_MULT = 0
NDefines.NAI.ACCEPTABLE_FRACTION_OF_INTEREST_PAYMENTS = 0.2
NDefines.NAI.ACCEPTABLE_FRACTION_OF_INTEREST_PAYMENTS_VASSAL = 0.25
NDefines.NAI.EDICT_VALUE_THRESHOLD = 50
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 150
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 10
NDefines.NAI.DEVELOPMENT_CAP_BASE = 50
NDefines.NAI.DEVELOPMENT_CAP_MULT = 3

NDefines.NGovernment.CENTRALIZE_STATE_ADM_COST = 50
NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 20.0